#!perl

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

# AUTHORITY
# DATE
# DIST
# VERSION

Perinci::CmdLine::Any->new(
    url => '/Git/Bunch/',
    subcommands => {
        check  => { url => '/Git/Bunch/check_bunch' },
        commit => { url => '/Git/Bunch/commit_bunch' },
        exec   => { url => '/Git/Bunch/exec_bunch' },
        ls     => { url => '/Git/Bunch/list_bunch_contents' },
        sync   => { url => '/Git/Bunch/sync_bunch' },

        "ls-bunches" => { url => '/Git/Bunch/list_bunches' },
    },
    log => 1,
    pass_cmdline_object => 1,
)->run;

1;
# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

To check the status of bunch (will do a 'git status' for each git repo inside
the bunch and report which repos are 'unclean', e.g. needs commit, has untracked
files, etc):

 % gitbunch check ~/repos

To synchronize bunch to another (will do a 'git pull/push' for each git repo,
and do an rsync for everything else):

 % gitbunch sync ~/repos /mnt/laptop/repos

=head2 Listing repositories

 % gitbunch ls        ; # just list each repository names
 % gitbunch ls -l     ; # list repository name, groups

=head2 Group-related commands

To list all defined groups:

 % gitbunch ls-groups    ; # just list the group names
 % gitbunch ls-groups -l ; # list each group's name, summary, and number of repos belonging to that group

To list

=head1 DESCRIPTION

A (git)bunch is a directory that contains a bunch of git repositories (as well
as dot non-git directories and regular files). This B<gitbunch> utility can help
you perform actions on some/all of the repositories in the bunch.


=head1 append:SEE ALSO

Other tools on CPAN to make it easier to manage multiple git repositories:
L<got> from L<App::GitGot>, L<group-git> from L<Group::Git>.
