#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

# workaround for current bug
$ENV{LOG} //= 1;

Perinci::CmdLine::Any->new(
    url => '/Git/Bunch/',
    subcommands => {
        ls     => { url => '/Git/Bunch/list_bunch_contents' },
        check  => { url => '/Git/Bunch/check_bunch'  },
        sync   => { url => '/Git/Bunch/sync_bunch'   },
        exec   => { url => '/Git/Bunch/exec_bunch'   },
    },
    log => 1,
)->run;

1;
# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

To check the status of bunch (will do a 'git status' for each git repo inside
the bunch and report which repos are 'unclean', e.g. needs commit, has untracked
files, etc):

 % gitbunch check ~/repos

To synchronize bunch to another (will do a 'git pull/push' for each git repo,
and do an rsync for everything else):

 % gitbunch sync ~/repos /mnt/laptop/repos
